/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package biblio;

import Entities.Account;
import Entities.BookItem;
import Services.AccountService;
import Services.BookItemService;
import Services.BookService;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class BookLending extends javax.swing.JFrame {

    /**
     * Creates new form BookLending
     */
    public BookLending() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        membersTAB = new javax.swing.JTable();
        memberID = new javax.swing.JTextField();
        usernameFilter = new javax.swing.JTextField();
        emailFilter = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        itemsTAB = new javax.swing.JTable();
        barcodeFilter = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        titleFilter = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        barcodeItem = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        membersTAB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "USERNAME", "EMAIL"
            }
        ));
        membersTAB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                membersTABMouseClicked(evt);
            }
        });
        membersTAB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                membersTABKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(membersTAB);

        memberID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        memberID.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        usernameFilter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                usernameFilterKeyReleased(evt);
            }
        });

        emailFilter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emailFilterKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Username");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Email");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 102, 0));
        jLabel1.setText("MEMBER ID");

        itemsTAB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BARCODE", "TITLE", "STATUS"
            }
        ));
        itemsTAB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemsTABMouseClicked(evt);
            }
        });
        itemsTAB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                itemsTABKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(itemsTAB);

        barcodeFilter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                barcodeFilterKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 153));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("BARCODE");

        titleFilter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                titleFilterKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 153));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("TITLE");

        barcodeItem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        barcodeItem.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 102, 0));
        jLabel6.setText("BARCODE");

        jButton1.setText("CONFIRM");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(usernameFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(emailFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(126, 126, 126)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23))
                            .addComponent(barcodeFilter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(memberID, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(barcodeItem, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31))
            .addGroup(layout.createSequentialGroup()
                .addGap(370, 370, 370)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(118, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(usernameFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(titleFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(28, 28, 28))
                    .addComponent(barcodeFilter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(barcodeItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(memberID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addGap(25, 25, 25)
                .addComponent(jButton1)
                .addGap(40, 40, 40))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            AccountService AS = new AccountService();
            ArrayList<Account> members = AS.getAllMembers();
            if(members!=null) {
                for(int i=0; i<members.size();i++) {
                    String id = String.valueOf(members.get(i).getId());
                    String username = members.get(i).getUsername();
                    String email = members.get(i).getEmail();
                    String tabData[] = {id,username,email};
                    DefaultTableModel tblModel = (DefaultTableModel) membersTAB.getModel();
                    tblModel.addRow(tabData);
                }
            }
            
            BookItemService BIS = new BookItemService();
            BookService BS = new BookService();
            ArrayList<BookItem> items = BIS.getAllBookItems();
            if(items!=null) {
                for(int i=0; i<items.size();i++) {
                    String title = BS.searchTitleByISBN(items.get(i).getBookISBN());
                    String barcode = items.get(i).getBarcode();
                    Boolean status = items.get(i).getStatus();
                    String available = "NOT AVAILABLE";
                    if (!status) available = "AVAILABLE";
                    String tabData[] = {barcode,title,available};
                    DefaultTableModel tblModel = (DefaultTableModel) itemsTAB.getModel();
                    tblModel.addRow(tabData);
                }
            }
        }
        catch(Exception e) {
                e.printStackTrace();
        }
    }//GEN-LAST:event_formWindowOpened

    private void membersTABMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_membersTABMouseClicked
        // TODO add your handling code here:
        int row = membersTAB.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)membersTAB.getModel();
        memberID.setText(model.getValueAt(row, 0).toString());
    }//GEN-LAST:event_membersTABMouseClicked

    private void usernameFilterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameFilterKeyReleased

        try {
            membersTAB.setModel(new DefaultTableModel(null,new String[]{"ID","USERNAME","EMAIL"}));
            DefaultTableModel tblModel = (DefaultTableModel) membersTAB.getModel();
            AccountService AS = new AccountService();
            ArrayList<Account> members = AS.searchAccountByUsername(usernameFilter.getText());
                for(int i=0; i<members.size();i++) {
                    String id = String.valueOf(members.get(i).getId());
                    String username = members.get(i).getUsername();
                    String email = members.get(i).getEmail();
                    String tabData[] = {id,username,email};
                    tblModel.addRow(tabData);
                }
        }
        catch(Exception e) {
                e.printStackTrace();
        }
    }//GEN-LAST:event_usernameFilterKeyReleased

    private void emailFilterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailFilterKeyReleased
        // TODO add your handling code here:
        try {
            membersTAB.setModel(new DefaultTableModel(null,new String[]{"ID","USERNAME","EMAIL"}));
            DefaultTableModel tblModel = (DefaultTableModel) membersTAB.getModel();
            AccountService AS = new AccountService();
            ArrayList<Account> members = AS.searchAccountByEmail(emailFilter.getText());
                for(int i=0; i<members.size();i++) {
                    String id = String.valueOf(members.get(i).getId());
                    String username = members.get(i).getUsername();
                    String email = members.get(i).getEmail();
                    String tabData[] = {id,username,email};
                    tblModel.addRow(tabData);
                }
        }
        catch(Exception e) {
                e.printStackTrace();
        }
    }//GEN-LAST:event_emailFilterKeyReleased

    private void barcodeFilterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_barcodeFilterKeyReleased
        // TODO add your handling code here:
        itemsTAB.setModel(new DefaultTableModel(null,new String[]{"BARCODE","TITLE","STATUS"}));
        BookItemService BIS = new BookItemService();
        BookService BS = new BookService();
        ArrayList<BookItem> items = BIS.searchBookItemsbyBarcode(barcodeFilter.getText());
        if(items!=null) {
            for(int i=0; i<items.size();i++) {
                String title = BS.searchTitleByISBN(items.get(i).getBookISBN());
                String barcode = items.get(i).getBarcode();
                Boolean status = items.get(i).getStatus();
                String available = "NOT AVAILABLE";
                if (!status) available = "AVAILABLE";
                String tabData[] = {barcode,title,available};
                DefaultTableModel tblModel = (DefaultTableModel) itemsTAB.getModel();
                tblModel.addRow(tabData);
            }
        }
    }//GEN-LAST:event_barcodeFilterKeyReleased

    private void titleFilterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_titleFilterKeyReleased
        itemsTAB.setModel(new DefaultTableModel(null,new String[]{"BARCODE","TITLE","STATUS"}));
        BookItemService BIS = new BookItemService();
        BookService BS = new BookService();
        ArrayList<BookItem> items = BIS.searchBookItemsbyTitle(titleFilter.getText());
        if(items!=null) {
            for(int i=0; i<items.size();i++) {
                String title = BS.searchTitleByISBN(items.get(i).getBookISBN());
                String barcode = items.get(i).getBarcode();
                Boolean status = items.get(i).getStatus();
                String available = "NOT AVAILABLE";
                if (!status) available = "AVAILABLE";
                String tabData[] = {barcode,title,available};
                DefaultTableModel tblModel = (DefaultTableModel) itemsTAB.getModel();
                tblModel.addRow(tabData);
            }
        }
    }//GEN-LAST:event_titleFilterKeyReleased

    private void itemsTABMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemsTABMouseClicked
        int row = itemsTAB.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)itemsTAB.getModel();
        barcodeItem.setText(model.getValueAt(row, 0).toString());
    }//GEN-LAST:event_itemsTABMouseClicked

    private void itemsTABKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_itemsTABKeyReleased
        int row = itemsTAB.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)itemsTAB.getModel();
        barcodeItem.setText(model.getValueAt(row, 0).toString());
    }//GEN-LAST:event_itemsTABKeyReleased

    private void membersTABKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_membersTABKeyReleased
        int row = membersTAB.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)membersTAB.getModel();
        memberID.setText(model.getValueAt(row, 0).toString());
    }//GEN-LAST:event_membersTABKeyReleased

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField barcodeFilter;
    private javax.swing.JTextField barcodeItem;
    private javax.swing.JTextField emailFilter;
    private javax.swing.JTable itemsTAB;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField memberID;
    private javax.swing.JTable membersTAB;
    private javax.swing.JTextField titleFilter;
    private javax.swing.JTextField usernameFilter;
    // End of variables declaration//GEN-END:variables
}
